# Generated by Django 3.2 on 2021-09-07 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='chapter',
            new_name='song',
        ),
    ]
